version: '3.8'

services:
  supply-service:
    image: 'ghcr.io/ozon-edu-csharp-2021/supply-service:main'
    hostname: supply_service
    ports:
      - "8080:80"
  emailing-service:
    image:  'ghcr.io/ozon-edu-csharp-2021/emailing-service:main'
    hostname: emailing_service
    ports:
      - "8080:80"
  employees-service:
    image: 'ghcr.io/ozon-edu-csharp-2021/employees-service:main'
    hostname: employees_service
    ports:
      - "8080:80"
  stock-api:
    image: 'ghcr.io/ozon-edu-csharp-2021/stock-api:main'
    hostname: stock_api
    ports:
      - "8080:80"
  
  
  
  